<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>异常 on XIZERO</title>
    <link>http://xizero.com/tags/%E5%BC%82%E5%B8%B8/index.xml</link>
    <description>Recent content in 异常 on XIZERO</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <atom:link href="http://xizero.com/tags/%E5%BC%82%E5%B8%B8/index.xml" rel="self" type="application/rss+xml" />
    
    <item>
      <title>Java 异常</title>
      <link>http://xizero.com/java/java-%E5%BC%82%E5%B8%B8/</link>
      <pubDate>Fri, 18 Nov 2016 18:20:00 +0800</pubDate>
      
      <guid>http://xizero.com/java/java-%E5%BC%82%E5%B8%B8/</guid>
      <description>

&lt;h2 id=&#34;定义&#34;&gt;定义&lt;/h2&gt;

&lt;p&gt;编译错误和运行时错误&lt;/p&gt;

&lt;h2 id=&#34;捕获异常&#34;&gt;捕获异常&lt;/h2&gt;

&lt;pre&gt;&lt;code class=&#34;language-java&#34;&gt;try {
//会产生异常的代码
} catch (Exception e){
//处理异常的代码
}
finally {
//不管是否产生异常都会执行的代码
}
&lt;/code&gt;&lt;/pre&gt;

&lt;h2 id=&#34;捕获多个异常&#34;&gt;捕获多个异常&lt;/h2&gt;

&lt;p&gt;1.7 支持单一的catch语句中捕获多个异常，每个异常之间使用管道符号 &lt;code&gt;|&lt;/code&gt;隔开&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-java&#34;&gt;catch (excepetion-1 | exception-2 ... e) {
    // 相同的处理代码
}
catch (excepetion-n e) {
    //其他的处理代码
}
&lt;/code&gt;&lt;/pre&gt;

&lt;h2 id=&#34;try-with-resource&#34;&gt;try-with-resource&lt;/h2&gt;

&lt;p&gt;1.7 之前的关闭资源时，会使用 finally ，但是关闭时产生异常会嵌套很多层。
1.7 添加 try-with-resource 语句，但是只用实现了 java.lang.AutoCloseable 的类才能关掉。&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-java&#34;&gt;//try ( resource ) { }
try (Statement stmt = con.createStatement()) { }
&lt;/code&gt;&lt;/pre&gt;

&lt;h2 id=&#34;java-lang-exception&#34;&gt;java.lang.Exception&lt;/h2&gt;

&lt;p&gt;Exception 覆盖了 toString () , 返回对异常的说明。
printStackTrace 方法 对 Exception 追踪，打印出对异常的描述。&lt;/p&gt;

&lt;p&gt;catch 语句的顺序很重要，JVM 根据其顺序来匹配异常，Exception 的 catch 语句必须放在最后。&lt;/p&gt;

&lt;h3 id=&#34;throw-和-throws&#34;&gt;throw 和 throws&lt;/h3&gt;

&lt;p&gt;throw : 用于抛出一个异常对象。
throws：用于方法名之后，表示该方法可能抛出异常的类型。&lt;/p&gt;

&lt;h3 id=&#34;自定义异常&#34;&gt;自定义异常&lt;/h3&gt;

&lt;p&gt;通过继承异常类，可以自定义异常。通过throw来抛出自定义异常。&lt;/p&gt;
</description>
    </item>
    
  </channel>
</rss>